version: '3.6'

services:
  one:
    image: willnotwish/at-the-races-dev:2.5.8
    secrets:
      - pubnub
    environment:
      RAILS_LOG_TO_STDOUT: 1
      DATABASE_HOST: mysql55
      DATABASE_NAME: atr_one
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      RAILS_MAX_THREADS: 10
      REDIS_URL: redis://redis:6379/11
    stdin_open: true
    tty: true
    user: nick
    volumes:
      - ./apps/atr-one:/app
      - atr-one-bundle:/usr/local/bundle
    working_dir: /app
    depends_on: 
      - mysql55
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3010:3000

  mysql55:
    image: mysql:5.5
    environment: 
      - MYSQL_DATABASE=atr_one
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      # The init sql files can sometimes be wiped out by the container.
      # For safety's sake, unmount them once the database is built.
      # - ./db/init-data/prod-restore:/docker-entrypoint-initdb.d
      - atr-one-mysql55-data:/var/lib/mysql
      # - ./db/init-data/split-files:/docker-entrypoint-initdb.d
      # - aperture-mysql55-data-feb-2023:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3316:3306

  sidekiq:
    image: willnotwish/at-the-races-dev:2.5.8
    secrets:
      - pubnub
    environment:
      RAILS_LOG_TO_STDOUT: 1
      DATABASE_HOST: mysql55
      DATABASE_NAME: atr_one
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      RAILS_MAX_THREADS: 10
      REDIS_URL: redis://redis:6379/11

    stdin_open: true
    tty: true
    user: nick
    volumes:
      - ./apps/atr-one:/app
      - atr-one-bundle:/usr/local/bundle
    working_dir: /app
    depends_on: 
      - mysql55
      - redis
    command: bundle exec sidekiq -q default

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - "5003:6379"    
  
  # kafka:
  #   image: apache/kafka:3.9.0
  #   ports:
  #     - 3317:3306

secrets:
  pubnub:
    file: ./apps/atr-one/config/secrets/pubnub.yml

volumes:
  atr-one-bundle:
  atr-one-mysql55-data:
  redis:
