version: '3.6'

services:
  one:
    image: willnotwish/at-the-races-dev-with-node:2.5.8
    secrets:
      - pubnub
      - centrifugo.json
    environment:
      RAILS_LOG_TO_STDOUT: 1
      DATABASE_HOST: mysql55
      DATABASE_NAME: atr_one
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      RAILS_MAX_THREADS: 10
      REDIS_URL: redis://redis:6379/11
      VITE_RUBY_HOST: one-vite
    stdin_open: true
    tty: true
    user: nick
    volumes:
      - ./apps/atr-one:/app
      - atr-one-bundle:/usr/local/bundle
      - vite-dev:/app/public/vite-dev
      - vite-test:/app/public/vite-test
    working_dir: /app
    depends_on: 
      - mysql55
      - one-vite
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3010:3000

  one-vite:
    image: willnotwish/at-the-races-dev-with-node:2.5.8
    # secrets:
    #   - pubnub
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
      DATABASE_HOST: mysql55
      DATABASE_NAME: atr_one
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      RAILS_MAX_THREADS: 10
      REDIS_URL: redis://redis:6379/11
      VITE_RUBY_HOST: 0.0.0.0
    stdin_open: true
    tty: true
    user: nick
    volumes:
      - ./apps/atr-one:/app
      - atr-one-bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - vite-dev:/app/public/vite-dev
      - vite-test:/app/public/vite-test
    working_dir: /app
    command: bundle exec vite dev -- --host 0.0.0.0
    ports:
      - 3036:3036


  mysql55:
    image: mysql:5.5
    environment: 
      - MYSQL_DATABASE=atr_one
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      # The init sql files can sometimes be wiped out by the container.
      # For safety's sake, unmount them once the database is built.
      # - ./db/init-data/prod-restore:/docker-entrypoint-initdb.d
      - atr-one-mysql55-data:/var/lib/mysql
      # - ./db/init-data/split-files:/docker-entrypoint-initdb.d
      # - aperture-mysql55-data-feb-2023:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3316:3306

  sidekiq:
    image: willnotwish/at-the-races-dev:2.5.8
    secrets:
      - pubnub
      - centrifugo.json
    environment:
      RAILS_LOG_TO_STDOUT: 1
      DATABASE_HOST: mysql55
      DATABASE_NAME: atr_one
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      RAILS_MAX_THREADS: 10
      REDIS_URL: redis://redis:6379/11

    stdin_open: true
    tty: true
    user: nick
    volumes:
      - ./apps/atr-one:/app
      - atr-one-bundle:/usr/local/bundle
    working_dir: /app
    depends_on: 
      - mysql55
      - redis
    command: bundle exec sidekiq -q default

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - "5003:6379"    

  centrifugo:
    # container_name: centrifugo
    image: centrifugo/centrifugo:v5
    secrets:
      - centrifugo.json
    command: centrifugo -c /run/secrets/centrifugo.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535 
  
secrets:
  pubnub:
    file: ./apps/atr-one/config/secrets/pubnub.yml
  centrifugo.json:
    file: ./apps/atr-one/config/secrets/centrifugo.json

volumes:
  atr-one-bundle:
  atr-one-mysql55-data:
  node_modules:
  redis:
  vite-dev:
  vite-test:
